/*
 * CrudSQL API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models CrudSQL provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taqi@mobix.biz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * QueryEntityWithRelations
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-12T09:59:16.176785Z[Europe/London]", comments = "Generator version: 7.11.0")
public class QueryEntityWithRelations {
  public static final String SERIALIZED_NAME_MAIN_ENTITY = "mainEntity";
  @SerializedName(SERIALIZED_NAME_MAIN_ENTITY)
  @javax.annotation.Nullable
  private Object mainEntity;

  public static final String SERIALIZED_NAME_RELATIONS = "relations";
  @SerializedName(SERIALIZED_NAME_RELATIONS)
  @javax.annotation.Nullable
  private Map<String, List<Object>> relations = new HashMap<>();

  public QueryEntityWithRelations() {
  }

  public QueryEntityWithRelations mainEntity(@javax.annotation.Nullable Object mainEntity) {
    this.mainEntity = mainEntity;
    return this;
  }

  /**
   * Get mainEntity
   * @return mainEntity
   */
  @javax.annotation.Nullable
  public Object getMainEntity() {
    return mainEntity;
  }

  public void setMainEntity(@javax.annotation.Nullable Object mainEntity) {
    this.mainEntity = mainEntity;
  }


  public QueryEntityWithRelations relations(@javax.annotation.Nullable Map<String, List<Object>> relations) {
    this.relations = relations;
    return this;
  }

  public QueryEntityWithRelations putRelationsItem(String key, List<Object> relationsItem) {
    if (this.relations == null) {
      this.relations = new HashMap<>();
    }
    this.relations.put(key, relationsItem);
    return this;
  }

  /**
   * Get relations
   * @return relations
   */
  @javax.annotation.Nullable
  public Map<String, List<Object>> getRelations() {
    return relations;
  }

  public void setRelations(@javax.annotation.Nullable Map<String, List<Object>> relations) {
    this.relations = relations;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryEntityWithRelations queryEntityWithRelations = (QueryEntityWithRelations) o;
    return Objects.equals(this.mainEntity, queryEntityWithRelations.mainEntity) &&
        Objects.equals(this.relations, queryEntityWithRelations.relations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mainEntity, relations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryEntityWithRelations {\n");
    sb.append("    mainEntity: ").append(toIndentedString(mainEntity)).append("\n");
    sb.append("    relations: ").append(toIndentedString(relations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("mainEntity");
    openapiFields.add("relations");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to QueryEntityWithRelations
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!QueryEntityWithRelations.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in QueryEntityWithRelations is not found in the empty JSON string", QueryEntityWithRelations.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!QueryEntityWithRelations.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `QueryEntityWithRelations` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QueryEntityWithRelations.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QueryEntityWithRelations' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QueryEntityWithRelations> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QueryEntityWithRelations.class));

       return (TypeAdapter<T>) new TypeAdapter<QueryEntityWithRelations>() {
           @Override
           public void write(JsonWriter out, QueryEntityWithRelations value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public QueryEntityWithRelations read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of QueryEntityWithRelations given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of QueryEntityWithRelations
   * @throws IOException if the JSON string is invalid with respect to QueryEntityWithRelations
   */
  public static QueryEntityWithRelations fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QueryEntityWithRelations.class);
  }

  /**
   * Convert an instance of QueryEntityWithRelations to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

