/*
 * CrudSQL API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models CrudSQL provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taqi@mobix.biz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ApiErrorResponse;
import org.openapitools.client.model.ApiModelSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SchemaApi
 */
@Disabled
public class SchemaApiTest {

    private final SchemaApi api = new SchemaApi();

    /**
     * Get model schema
     *
     * Returns the schema information for a specific model including fields and relationships
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void modelSchemaGetTest() throws ApiException {
        String model = null;
        ApiModelSchema response = api.modelSchemaGet(model);
        // TODO: test validations
    }

}
